### ISSUE TITLE
100% CPU usage during `imageproc::window::display_image` on Linux

### ISSUE THREAD

**Issue by notgull** [image-rs/imageproc#504] opened 2022-07-30 18:58 UTC
While running the `display_image` function, one of the CPU's on my computer suddenly rockets up to using 100% of the CPU.

![100% usage on one CPU](https://i.imgur.com/hKdGfIq.png)

Looking into the backtraces while running `gdb`, it appears to be happening during `sdl2` event retrieval. However, a brief investigation into `sdl2`'s codebase yields nothing that would cause this, and I'm unsure if this issue originates in `imageproc` or in one of its dependencies.

[Here is the program I'm using it in](https://github.com/bread-graphics/bentley-ottmann/blob/master/examples/rasterize.rs), although I doubt it's that.

**Comment by theotherphil** [comment] 2022-08-02 05:42
I’ve never used sdl2 myself, but from a quick look at the code for this function it looks like the issue is using poll_iter rather than wait_iter.

I won’t have time to work on fixing this myself, but would be very happy to accept a PR if this works.

https://github.com/image-rs/imageproc/blob/0929335c17a08016ca1a0443dbb1e4d1b6a3f229/src/window.rs#L129

https://docs.rs/sdl2/latest/sdl2/struct.EventPump.html

**Comment by theotherphil** [comment] 2024-03-16 07:29
Fixed by https://github.com/image-rs/imageproc/pull/515

**Closed by theotherphil** 2024-03-16 07:29 UTC
